[package]
name = "rusty_spine"
version = "0.1.0"
edition = "2021"
description = "Spine runtime for Rust (and wasm!) transpiled from the official C Runtime."
homepage = "https://github.com/jabuwu/rusty_spine"
repository = "https://github.com/jabuwu/rusty_spine"
readme = "readme.md"
license-file = "LICENSE"

[dependencies]
libc = { version = "0.2", optional = true }

[dev-dependencies]
transpiler = { path = "./transpiler" }
bevy = "0.8"

[profile.dev.package."*"]
opt-level = 3

[features]
use_libc = [ "libc" ]