[package]
name = "rusty_spine"
version = "0.2.0"
edition = "2021"
description = "Spine runtime for Rust (and wasm!) transpiled from the official C Runtime."
homepage = "https://github.com/jabuwu/rusty_spine"
repository = "https://github.com/jabuwu/rusty_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
]

[dependencies]
libc = { version = "0.2", optional = true }
egui = { version = "0.19", optional = true }
egui_extras = { version = "0.19", optional = true }

[dev-dependencies]
transpiler = { path = "./transpiler" }
bevy = "0.8"
bevy_egui = "0.16"

[profile.dev.package."*"]
opt-level = 3

[features]
default = [ "draw_functions" ]
use_libc = [ "libc" ]
draw_functions = []
egui_debugger = [ "egui", "egui_extras" ]
